apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: employee-dev
  labels:
    app: employee-service
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-service
      tier: frontend
  template:
    metadata:
      labels:
        app: employee-service
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: employee-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: '0.1'
            memory: "128Mi"
          limits:
            cpu: '0.2'
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10