apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: employee-prod
  labels:
    app: employee-service
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee-service
      tier: frontend
  template:
    metadata:
      labels:
        app: employee-service
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: nginx:alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: '0.2'
            memory: "256Mi"
          limits:
            cpu: '0.3'
            memory: "384Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: static-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-config
        configMap:
          name: frontend-config
      - name: static-content
        configMap:
          name: frontend-content