apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: employee-prod
  labels:
    app: employee-service
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: employee-service
    tier: frontend